// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQ2PRGKMCfDXWNtGka2vijBz9IHYx428',
    appId: '1:922983099806:android:07d69c641ad634ac14fa8f',
    messagingSenderId: '922983099806',
    projectId: 'make-friends-7f028',
    storageBucket: 'make-friends-7f028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQTrFjbee3qUlD4ZfWakH09GIaUbvXY4',
    appId: '1:922983099806:ios:8f482a4ee61366c014fa8f',
    messagingSenderId: '922983099806',
    projectId: 'make-friends-7f028',
    storageBucket: 'make-friends-7f028.appspot.com',
    androidClientId: '922983099806-aclj89p2sr8ibfmhkdmfnltn6ablgglh.apps.googleusercontent.com',
    iosClientId: '922983099806-m5sfs4dclaomhp7hcv1nrpflu6k0iumh.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeFriendsApp',
  );
}
